name: Continuous Delivery

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: CI='false' npm run build

      - name: Environment Setting
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "REACT_APP_SERVER_UR=${{ secrets.REACT_APP_SERVER_UR }}" >> .env
          echo "REACT_APP_MAP_ACCESS_TOKEN=${{ secrets.REACT_APP_MAP_ACCESS_TOKEN }}" >> .env
          echo "REACT_APP_MAP_STYLE=${{ secrets.REACT_APP_MAP_STYLE }}" >> .env
          echo "REACT_APP_GOOGLE_SEARCH_KEY=${{ secrets.REACT_APP_GOOGLE_SEARCH_KEY }}" >> .env
          cat .env

      - name: Deploy
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://healthier-frontend
